name: checkin

on: 
  push: # push触发
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '* * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: checkin
      env:
        openid: ${{secrets.OPENID}}
        sid: ${{secrets.SID}}
        sex: ${{secrets.SEX}}
        name: ${{secrets.NAME}}
        addr1: ${{secrets.ADDR1}}
        addr2: ${{secrets.ADDR2}} 
      run: python main.py
